services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wizhippo\WizhippoDeferredVisibilityBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations}'

    Wizhippo\WizhippoDeferredVisibilityBundle\Service\DeferredVisibilityService:
        arguments:
            $supportedTypeIds: '%wizhippo_deferred_visibility_bundle.supported_type_ids%'
